name: "Mod (.geode or .dll)"
description: "Ryzen will get all info from main section data you write."

labels: "mod"
title: "Unnamed Mod"

body:

- type: textarea
  attributes:
    label: "Main Section"
    value: |
      [main]
      
      ; Description about your mod in 1-2 text lines 
      desc = Just cool mod, trust me
      
      ; If mod not yours or whatever (not important key)
      developer = 

      ; Mod download link
      download_link = 
      
      ; Custom link to logo image  (not important key)
      logo_url = 
      
      ; not important key
      website_link = 
      
      ; not important key
      custom_bg_link = 
      
      ; not important key
      overlay_link = 
  validations:
    required: true
    
- type: textarea
  attributes:
    label: "body:"
    value: |
      # My mod
      soo thats template text ya here you can write your content
  validations:
    required: true
