name: "Resourses Mod (.zip texture pack)"
description: "Fill important info about yor resource pack in main section."

labels: "pack,gd-2.206"
title: "Unnamed Resource Pack"

body:

- type: textarea
  attributes:
    label: "Main Section"
    value: |
      [main]
      
      ; Description about your mod in 1-2 text lines 
      desc = Just cool texture pack, trust we
      
      ; If mod not yours or whatever (not important key)
      developer = 

      ; Pack download link!
      download_link = 
      
      ; logo image (not important key)
      logo_url = 
      
      ; not important key
      website_link = 
      
      ; not important key
      custom_bg_link = 
      
      ; not important key
      overlay_link = 
  validations:
    required: true
    
- type: textarea
  attributes:
    label: "body:"
    value: |
      # My tp
      soo thats template text ya here you can write your content
  validations:
    required: true
