---
name: Add mod
description: base template with ini mod info
title: Unnamed mod entry
labels: 'mod'

body:
- type: textarea
  attributes:
    label: "[mod]"
    value: |
      ; name of target file in release
      file = noname.mod.geode
      ; repository
      repo = user/mod
      ; u can set exact version if it really needs
      release_tag = latest
      ; small description about ur mod
      desc = No description provided...
    render: ini
  validations:
    required: true
---
