---
name: Add mod
description: base template with ini mod info
title: Unnamed Mod
labels: ['mod', 'invalid']

body:
- type: textarea
  attributes:
    label: "[mod]"
    value: |
      ; name of target file in release
      file = noname.mod.geode
      
      ; repository
      repo = user/mod
      
      ; u can set exact version if it really needs
      release_tag = latest
      
      ; (if its not hosted at releases) Direct link up to file (https://files.hosting/noname.mod.geode)
      download_link = 
  validations:
    required: true
---
