---
name: Add Modification (.geode/.dll/.so)
description: base template with ini mod info
title: Unnamed Mod
labels: ['mod']

body:
- type: textarea
  attributes:
    label: "[mod]"
    value: |
      ; name of target file in release
      file = noname.mod.geode
      
      ; repository
      repo = user/mod
      
      ; u can set exact version if it really needs
      release = latest
  validations:
    required: true
---
