---
name: Add Open Source Modification (.geode/.dll)
description: Ryzen will getting info from your repository.
title: Unnamed Mod
labels: ['mod']

body:
- type: textarea
  label: ""
  attributes:
    value: |
      ; name of target file in release
      file = noname.mod.geode
      
      ; repository
      repo = user/mod
      
      ; u can set exact version if it really needs
      release = latest
  validations:
    required: true
---
