name: Exec Command
on:
  issue_comment:
    types:
      - created
      - edited
permissions:
  contents: write 
  issues: write 
jobs:
  CheckUserPermission:
    runs-on: ubuntu-latest
    steps:
      - name: "Check user permission" 
        uses: actions-cool/check-user-permission@v2
  verify:
    needs: CheckUserPermission
    runs-on: ubuntu-latest
    if: github.event.comment.body == '!verify'
    steps:
      - name: "Verify mod"
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.issue.id }}
          prerelease: false
      - name: "React to comment"
        uses: GrantBirki/comment@v2.0.10
        with:
          comment-id: ${{ github.event.comment.id }}
          issue-number: ${{ github.event.issue.number }}
          reactions: eyes

  unverify:
    needs: CheckUserPermission
    runs-on: ubuntu-latest
    if: github.event.comment.body == '!unverify'
    steps:
      - name: "Unverify mod"
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.issue.id }}
          prerelease: true
      - name: "React to comment"
        uses: GrantBirki/comment@v2.0.10
        with:
          comment-id: ${{ github.event.comment.id }}
          issue-number: ${{ github.event.issue.number }}
          reactions: eyes
