name: Exec Command
on:
  issue_comment:
    types:
      - created
      - edited
permissions:
  contents: write 
  issues: write 
jobs:
  CheckUserRermission:
    runs-on: ubuntu-latest
    steps:
      - name: "Check user permission" 
        uses: actions-cool/check-user-permission@v2
  Verify:
    needs: CheckUserRermission
    runs-on: ubuntu-latest
    steps:
      - name: "Is Verify command" 
        if: github.event.issue_comment.comment.body == "!verify"
        run: echo github.event.issue_comment.comment.body
      - name: "Verify mod"
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.issue.id }}
          prerelease: false
