name: Release Issued Mod
on:
  issues:
    types:
      - reopened
      - opened
permissions:
  contents: write 
  issues: write 
jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - name: "Release"
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.issue.id }}
          name: ${{ github.event.issue.title }}
