name: Release Issued Mod
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  Main:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.issue.id }}
          release_name: ${{ github.event.issue.title }}
