name: Add label
on:
  issue_comment:
    types:
      - created
      - edited
permissions:
  contents: write 
  issues: write 
env: 
 labels: ${{ join(github.event.comment.body, ' ') }}
jobs:
  Main:
   runs-on: ubuntu-latest 
   if: github.event.comment.user.id == github.event.issue.user.id && startsWith(github.event.comment.body, '!setlabels ') && false == contains(github.event.comment.body, 'verified') 
   steps:
    - run: echo ${{ env.labels }}
    - name: Toggle label
      uses: actions-cool/issues-helper@v3
      with:
       actions: 'toggle-labels'
       token: ${{ secrets.GITHUB_TOKEN }}
       issue-number: ${{ github.event.issue.number }}
       labels: ${{ env.labels }}
